### ISSUE TITLE
Publish release with jar file for use in helm chart

### ISSUE THREAD

**Issue by sblack4** [Graylog2/graylog-plugin-integrations#721]
# Description

Please publish the complied jar with the releases 

## What

A jar file

## Why

I use this helm chart https://github.com/KongZ/charts/tree/main/charts/graylog

It allows for the addition of plugins by simply adding the URL to the jar in the values file: 
```
  plugins:
    - name: graylog-plugin-slack-notification-3.1.0.jar
      url: https://github.com/omise/graylog-plugin-slack-notification/releases/download/v3.1.0/graylog-plugin-slack-notification-3.1.0.jar
```

**Comment by sblack4** [comment]
My quick hack-around was to just build a container with the plugin. Feel free to use/fork
- repo: https://github.com/rhythmictech/docker-graylog-integrations-plugin
- image: https://github.com/orgs/rhythmictech/packages/container/package/graylog-integrations-plugin

**Comment by jalogisch** [comment]
the Graylog Docker Image is also available with Enterprise and Integrations plugins already included: 

https://hub.docker.com/r/graylog/graylog-enterprise

In addition to that with this PR: https://github.com/Graylog2/graylog-docker/pull/148 the ability is given to define external plugin dir. What is not yet documented in the final docs because this PR is pending for review: https://github.com/Graylog2/documentation/pull/1057

The next option would be to sneak into the image to see how that is done an implement that yourself:

https://github.com/Graylog2/graylog-docker/blob/4.0/docker/enterprise/Dockerfile#L55-L63
