### ISSUE TITLE
Invalid format using PAN OS input

### ISSUE THREAD

**Issue by edward-marrufo** [Graylog2/graylog-plugin-integrations#816]
## Expected Behavior

When attempting to create an input in Graylog using PAN OS 9 input I would expect to see it work with the provided dates in the message.

## Current Behavior

Currently the first time stamp is working normally and the second time stamp (event created) shows "invalid format" in the server logs.
## Steps to Reproduce (for bugs)

1. See HS-382974779 for supporting information.

**Comment by bernd** [comment]
I moved this issue from the server repository.

**Comment by kmerz** [comment]
I did some research on this issue since I suspected a wrong pipeline rule.

After some research I found that the PaloAlto9x input is overriding the timestamp field here:

https://github.com/Graylog2/graylog-plugin-integrations/blob/master/src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java#L85

which leads to the problem that the `timestamp` field is no longer a DateTime object but the plain string,
as it can be seen in the test:

https://github.com/Graylog2/graylog-plugin-integrations/blob/master/src/test/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplatesTest.java#L86

The user sees this problem when he tries to parse the timestamp field in a pipeline rule:
```
2021-04-21T16:03:23.034+02:00 WARN  [ProcessBufferProcessor] Unable to process message <55aaf7a0-a2aa-11eb-9624-005056a1a599>: org.graylog.plugins.pipelineprocessor.ast.exceptions.FunctionEvaluationException: java.lang.IllegalArgumentException: Invalid format: "2021/04/21 16:03:08" is malformed at "/04/21 16:03:08" at
```

Since he could not send any message to the system it is unclear to me what happens after the pipeline processing. Perhaps there some cleanup with the timestamp is made.

**Comment by waab76** [comment]
The error is getting thrown from this line of code: https://github.com/Graylog2/graylog2-server/blob/1b84172433551fcf53fb91cb190685f74[…]raylog/plugins/pipelineprocessor/functions/dates/ParseDate.java

Maybe it wouldn't be going down to that line of code if the timestamp field were stored as a `DateTime` instead of a `String`, but the fact remains that the parsing (of what looks like a valid timestamp string) is failing

I had a suspicion that it was failing due to the timestamp string not matching the expected pattern for the locale, but I have no idea where the locale used in `ParseDate` is coming from

But in all our testing (presumably using en_US as the locale), this hasn't been an issue

Maybe the customer in DE has a different locale in Graylog and that's causing the timestamp parse to fail because Palo devices always use a non-DE timestamp format?  I worry that if we tried to do the same timestamp parsing in the codec that is now being done further down the processing chain, we'd just get the exact same failure earlier because we'd still have a mismatch between the expected timestamp format and the actual timestamp format.

**Comment by bernd** [comment]
@waab76 @kmerz The problem is the following:

The palo parser sets a `timestamp` field in the fields map which has type string. This is the event timestamp of the message and has been parsed from the CSV message.

https://github.com/Graylog2/graylog-plugin-integrations/blob/e6758b41d33eed549a47e9e395a6c88893c53751/src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xTemplates.java#L284

Here in line 81 we create a new `Message` object with `p.timestamp()` as timestamp parameter. The `p.timestamp()` is the parsed syslog timestamp. After that we run into the switch statement and call `message.addFields()` with the result of `fieldProducer.parseFields()`. That result includes a `timestamp` field which is a string (as described abot) and will overwrite the previous `DateTime`  timestamp field with a string value.

https://github.com/Graylog2/graylog-plugin-integrations/blob/e6758b41d33eed549a47e9e395a6c88893c53751/src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java#L74-L88

If there is no pipeline rule that tries to do something with the timestamp, the timestamp will be set to "now" before serializing the message for indexing here:

https://github.com/Graylog2/graylog2-server/blob/7929c28ca96b596acf04caf92d7c13d258878760/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L420-L429

That means the timestamp will be wrong.

If a pipeline rule tries to do something with the `timestamp` field and expects a `DateTime` object or a string in a specific format, it will fail earlier.

So I think the main issue here is, that the PaloAlto parsers will always overwrite the `timestamp` field in the `Message` object with a string and that will result in a message with the wrong timestamp ("now" at time of serializing the message for indexing).

The question now is how we can fix that in a backwards compatible way.

**Comment by waab76** [comment]
Thanks for the detailed explanation @bernd.  I guess what we need to do then is find a way to ensure that the `timestamp` field in the message is written as a `DateTime` with the proper value from the incoming PAN data before the message exits the PAN codec.

We could do this either by adding a datetime to the existing types that the template handles or by converting the `timestamp` string to a `DateTime` after the message has been fully populated.

**Comment by waab76** [comment]
Re-opening to await backport to 4.0 branch
